### ISSUE TITLE
MinTube crashes when trying to play videos. 

### ISSUE THREAD

**Issue by Poomex** [imshyam/mintube#17]
MinTube 0.95 from F-Droid crashes immediately when trying to play any video. I have tried to change quality settings but no luck. 
I'm running Android 7.1.1

**Comment by pExeen** [comment]
Same probleme here but the version 0.91 works

**Comment by conspacer** [comment]
Same problem. Crash on VDO play. 0.95 from F-Droid on Android 7.1.1 (LineageOS).
Maybe Alphabet's new TOS for YT blocking something?

**Comment by imshyam** [comment]
I will start working on Android 7 compatibility ASAP. Meanwhile, feel free to contribute.

**Comment by MargosDezerian** [comment]
I have the same problem on Android 7.1.1 with my BQ Aquaris X5 Plus.The app didn't even start a video and crashes all the time on version 0.93.Version 0.91 is also working but I can't close the video by draging it to the x on the bottom of the screen(nothing happens when i do that),I have to close it through the status bar notification.On my other device Asus Zenfone 2 Laser with Android 6.0.1 all is working fine with the newest version.Nice app btw,that thing will rock heavy imo when all the bugs are mastered and all the options are integrated.

**Comment by imshyam** [comment]
Fixed the issue with Android 7. Should work fine now.

**Comment by thorrpl** [comment]
Hello,
Could to reopen this issue? I'm still faceing this problem with version 0.95 on android 7.0 (I installed it today).
Any advise?

**Comment by imshyam** [comment]
Hi @thorrpl, I'll fix it and will update on F-Droid ASAP.

**Comment by imshyam** [comment]
@thorrpl , also check [this](http://bit.ly/mintube) out.

**Comment by thorrpl** [comment]
It's working! Thanks a lot.

**Comment by imshyam** [comment]
F-Droid doesn't have the updated apk.

I'll update it on F-Droid as well, till then use [bit.ly/mintube](http://bit.ly/mintube).

**Comment by liobash** [comment]
```05-29 12:42:35.185  7453  7453 E AndroidRuntime: FATAL EXCEPTION: main
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Process: com.shapps.mintubeapp, PID: 7453
05-29 12:42:35.185  7453  7453 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.shapps.mintubeapp.PlayerService@198fbc with Intent { act=com.shapps.ytube.action.playingweb cmp=com.shapps.mintubeapp/.PlayerService (has extras) }: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class android.widget.ImageView
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3416)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6293)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class android.widget.ImageView
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class android.widget.ImageView
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.shapps.mintubeapp.PlayerService.a(PlayerService.java:419)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.shapps.mintubeapp.PlayerService.onStartCommand(PlayerService.java:220)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3399)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6293)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.shapps.mintubeapp:drawable/arrow_drop_up with resource ID #0x7f02004b
05-29 12:42:35.185  7453  7453 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/arrow_drop_up.xml from drawable resource ID #0x7f02004b
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:972)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:931)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:157)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:145)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:141)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
05-29 12:42:35.185  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at com.shapps.mintubeapp.PlayerService.a(PlayerService.java:419)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at com.shapps.mintubeapp.PlayerService.onStartCommand(PlayerService.java:220)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3399)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6293)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Float format error when parsing: 	
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.util.PathParser.nCreatePathDataFromString(Native Method)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.util.PathParser.-wrap1(PathParser.java)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.util.PathParser$PathData.<init>(PathParser.java:74)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1633)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:702)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:607)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1229)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1202)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
05-29 12:42:35.199  7453  7453 E AndroidRuntime: 	... 32 more```
